/* Create Doctor table */
CREATE TABLE DOCTOR(
Doctor_ID CHAR(10) NOT NULL,
Name VARCHAR(30) NOT NULL,
Phone CHAR(25) NOT NULL,
Specialty_Num CHAR(10) NOT NULL,
Supervisor_ID CHAR(10) NOT NULL,
CONSTRAINT PK_DR PRIMARY KEY (Doctor_ID),
CONSTRAINT UQ_DR UNIQUE (Doctor_ID),
CONSTRAINT FK_SPLTY FOREIGN	KEY	(Specialty_Num)
REFERENCES SPECIALTY(Specialty_Num)
);

/* Create Patient table */
CREATE TABLE PATIENT(
Patient_ID CHAR(10) NOT NULL,
Name VARCHAR(30) NOT NULL,
Phone CHAR(25) NOT NULL,
Email CHAR(50),
Address CHAR(120) NOT NULL,
Added_Date DATE NOT NULL,
Doctor_ID CHAR(10) NOT NULL,
CONSTRAINT PK_PATNT	PRIMARY	KEY	(Patient_ID),
CONSTRAINT UQ_PATNT	UNIQUE (Patient_ID),
CONSTRAINT FK_D FOREIGN KEY (Doctor_ID) REFERENCES DOCTOR(Doctor_ID)
); 

/* Create Appointment table */
CREATE TABLE APPOINTMENT(
Appointment_ID CHAR(10) NOT NULL,
Patient_ID CHAR(10) NOT NULL,
Doctor_ID CHAR(10) NOT NULL,
Appointment_Date DATE NOT NULL,
Blood_Pressure INT NOT NULL,
Weight DECIMAL(5, 2) NOT NULL,
Treatment_Notes CHAR(230) NOT NULL,
CONSTRAINT PK_APP PRIMARY KEY (Appointment_ID),
CONSTRAINT UQ_APP UNIQUE (Appointment_ID),
CONSTRAINT FK_D_APP FOREIGN KEY (Doctor_ID) REFERENCES DOCTOR(Doctor_ID),
CONSTRAINT FK_PATNT_APP FOREIGN KEY (Patient_ID) REFERENCES	PATIENT(Patient_ID)
);

/* Create Specialty table */
CREATE TABLE SPECIALTY(
Specialty_Num CHAR(10) NOT NULL,
NAME VARCHAR(30),
CONSTRAINT PK_SPLTY_N PRIMARY KEY (Specialty_Num),
CONSTRAINT UQ_SPLTY_N UNIQUE (Specialty_Num)
);

/* Create Patient_Medicine table */
CREATE TABLE PATIENT_MEDICINE(
Appointment_ID CHAR(10) NOT NULL,
Medicine_ID CHAR(10) NOT NULL,
CONSTRAINT PK_APP_M PRIMARY KEY (Appointment_ID, Medicine_ID),
CONSTRAINT UQ_APP_M UNIQUE (Appointment_ID, Medicine_ID),
CONSTRAINT FK_APP FOREIGN KEY (Appointment_ID) REFERENCES APPOINTMENT(Appointment_ID),
CONSTRAINT FK_M FOREIGN KEY (Medicine_ID) REFERENCES MEDICINE(Medicine_ID)
);

/* Create Medicine table */
CREATE TABLE MEDICINE(
Medicine_ID CHAR(10) NOT NULL,
Name VARCHAR (50) NOT NULL,
CONSTRAINT PK_M PRIMARY KEY (Medicine_ID),
CONSTRAINT UQ_M UNIQUE (Medicine_ID)
);

/* Create Patient_Allergy table */
CREATE TABLE PATIENT_ALLERGY(
Allergy_ID CHAR(10) NOT NULL,
Patient_ID CHAR(10) NOT NULL,
CONSTRAINT PK_A_PATNT PRIMARY KEY (Allergy_ID, Patient_ID),
CONSTRAINT UQ_A_PATNT UNIQUE (Allergy_ID, Patient_ID),
CONSTRAINT FK_A FOREIGN	KEY	(Allergy_ID) REFERENCES ALLERGY(Allergy_ID),
CONSTRAINT FK_PATNT FOREIGN KEY (Patient_ID) REFERENCES	PATIENT(Patient_ID)
);

/* Create Allergy table */
CREATE TABLE ALLERGY(
Allergy_ID CHAR(10) NOT NULL,
Name VARCHAR(35) NOT NULL,
CONSTRAINT PK_A	PRIMARY	KEY	(Allergy_ID),
CONSTRAINT UQ_A UNIQUE (Allergy_ID)
);


SELECT * FROM SPECIALTY;
SELECT * FROM DOCTOR;
SELECT * FROM PATIENT;
SELECT * FROM ALLERGY;
SELECT * FROM PATIENT_ALLERGY;
SELECT * FROM APPOINTMENT;
SELECT * FROM MEDICINE;
SELECT * FROM PATIENT_MEDICINE;
